Trys-Ketch/trys-ketch-server

- src/main/java/com/project/trysketch/global/dto/MsgResponseDto.java
- src/main/java/com/project/trysketch/global/dto/ResponseMsgDto.java
- src/main/java/com/project/trysketch/global/jwt/JwtAuthFilter.java
- src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
- src/main/java/com/project/trysketch/user/controller/UserController.java
- src/main/java/com/project/trysketch/user/dto/KakaoUserRequstDto.java
- src/main/java/com/project/trysketch/user/entity/User.java
- src/main/java/com/project/trysketch/user/repository/UserRepository.java
- src/main/java/com/project/trysketch/user/service/KakaoService.java
- src/main/java/com/project/trysketch/user/service/UserService.java
feature/2 -> develop
- OAuth2.0 카카오톡 로그인 구현
> [FEAT] OAuth2.0 카카오톡 로그인 구현

- src/main/java/com/project/trysketch/gameroom/controller/GameRoomController.java
- src/main/java/com/project/trysketch/gameroom/dto/request/GameRoomRequestDto.java
- src/main/java/com/project/trysketch/gameroom/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/gameroom/entity/GameRoom.java
- src/main/java/com/project/trysketch/gameroom/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/gameroom/repository/GameRoomRepository.java
- src/main/java/com/project/trysketch/gameroom/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
- src/main/java/com/project/trysketch/user/dto/UserResponseDto.java
feature/7-> develop
- GameRoom Create api 추가
- GameRoom User 관련 파일 추가
> [FEAT] GameRoom 생성 관련 기능 추가

- src/main/java/com/project/trysketch/gameroom/controller/GameRoomController.java
- src/main/java/com/project/trysketch/gameroom/dto/response/GameRoomCreateResponseDto.java
- src/main/java/com/project/trysketch/gameroom/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/gameroom/entity/GameRoom.java
- src/main/java/com/project/trysketch/gameroom/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/gameroom/repository/GameRoomRepository.java
- src/main/java/com/project/trysketch/gameroom/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
- src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
- src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
- src/main/java/com/project/trysketch/redis/config/RedisConfig.java
- src/main/java/com/project/trysketch/redis/dto/NonMember.java
- src/main/java/com/project/trysketch/redis/dto/NonMemberNickRequestDto.java
- src/main/java/com/project/trysketch/redis/repositorty/RedisAccessTokenRepository.java
- src/main/java/com/project/trysketch/redis/service/RedisService.java
- src/main/java/com/project/trysketch/suggest/AdjectiveEntity.java
- src/main/java/com/project/trysketch/suggest/AdjectiveRepository.java
- src/main/java/com/project/trysketch/suggest/NounEntity.java
- src/main/java/com/project/trysketch/suggest/NounRepository.java
- src/main/java/com/project/trysketch/user/controller/UserController.java
- src/main/java/com/project/trysketch/user/entity/RandomNick.java
- src/main/java/com/project/trysketch/user/repository/RandomNickRepository.java
- src/main/java/com/project/trysketch/user/service/KakaoService.java
- src/main/java/com/project/trysketch/user/service/UserService.java
feature/11-> develop
- gameroom패키지 gameroom 입장관련 api기능 구현
- global-exception-StatusMsgCode 내부 code 추가
> [FEAT] GameRoom 입장 관련 기능 추가 (#11)

- build.gradle
- src/main/java/com/project/trysketch/global/config/WebRtcConfig.java
- src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
- src/main/java/com/project/trysketch/global/rtc/ChatMessage.java
- src/main/java/com/project/trysketch/global/rtc/Room.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/global/rtc/WebSocketMessage.java
feature/10-> develop
- WebRtcConfig, WebSocketConfig 생성
- SignalingHandler 러프하게 작성, 추후 수정 예정
클라이언트와 테스트 필요합니다.
> [FEAT] WebRTC, WebSocket 관련 Signaling Server 구축

- src/main/java/com/project/trysketch/gameroom/controller/GameRoomController.java
- src/main/java/com/project/trysketch/gameroom/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/gameroom/entity/GameRoom.java
- src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
- src/main/java/com/project/trysketch/global/config/WebRtcConfig.java
- src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
- src/main/java/com/project/trysketch/global/rtc/ChatMessage.java
- src/main/java/com/project/trysketch/global/rtc/Room.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/global/rtc/WebSocketMessage.java
feature/16-> develop
- GameRoomController 내부 getAllGameRoom 메소드 추가
- GameRoomResponseDto 인원수 필드 추가
- ★GameRoom 엔티티 GameRoomUser 연관관계 설정
- GameRoomService 내부 getAllGameRoom 메소드 추가
> [FEAT] GameRoom 조회 관련 기능 추가 (#16)

- src/main/java/com/project/trysketch/gameroom/controller/GameRoomController.java
- src/main/java/com/project/trysketch/gameroom/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/gameroom/entity/GameRoom.java
- src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/rtc/ChatMessage.java
- src/main/java/com/project/trysketch/global/rtc/Room.java
feature/20-> develop
- GameRoomService 내부 exitGameRoom 메소드 생성
- GameRoom 엔티티 host 필드 nullable 제거
> [FEAT] GameRoom 삭제 관련 기능 추가 (#20) 

- src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
- src/main/java/com/project/trysketch/image/ImageController.java
- src/main/java/com/project/trysketch/image/ImageLikeRepository.java
- src/main/java/com/project/trysketch/image/ImageService.java
feature/23 -> develop
- 그림에 좋아요 취소 기능 추가
- 비회원 진입 위해 HttpServlet로부터 claim 받아오는 것으로 변경
> [FEAT] S3 관련 - 그림 좋아요 취소기능 추가 및 httpservlet로 변경 (#23)

- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/maingame/controller/GameController.java
- src/main/java/com/project/trysketch/maingame/entity/GameInfo.java
- src/main/java/com/project/trysketch/maingame/service/GameService.java
- global-exception-StatusCode 메세지 코드 추가
- maingame 패키지 추가
- maingame - controller, entity, service 추가
> [FEAT] 게임 메인 로직 구현 (#26)

- src/main/java/com/project/trysketch/image/Scheduler.java
feature/29 -> develop
- scheduler 이용한 삭제기능 2분 -> 5시간으로 변경.
> 리소스 낭비하지 않도록 scheduler 주기 2분 -> 5시간으로 변경 (#29)

- src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
- src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/redis -> develop
- 게임 방 나가기 비회원 추가 및 코드 일부 변경
- webSecurityConfig 설정에 header 이름 잘못 지정한 부분 변경
- service 로직에 주석 새로운 방식으로 시도
> [FIX] 기능 추가 및 연관된 로직 병합 (#5)

- src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
> [FEAT] 총 페이지수 가져오기

- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/global/config/WebRtcConfig.java
- src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
- src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/43-> develop
- webSessionId 변경
- WebRTC 관련 CORS 설정
클라이언트와 테스트 필요
> [FIX] 변수명 변경, WebRTC 관련 CORS 설정

- src/main/java/com/project/trysketch/service/GameRoomService.java
- 기존 gameRoomList만 반환하던 getAllGameRoom 메소드가 gameRoomList와 LasgPage를 함께 반환하도록 변경
> [FEAT] getAllGameRoom 반환정보 수정 (#47)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/dto/response/GameStartResponseDto.java
- src/main/java/com/project/trysketch/entity/GameInfo.java
- src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/repository/GameInfoRepository.java
- src/main/java/com/project/trysketch/service/GameService.java
> [FEAT] 게임 시작 로직 구현 (#26)

- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/entity/GameInfo.java
- src/main/java/com/project/trysketch/redis/service/RedisService.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/redis -> develop
- 회원, 비회원 모듈 로직 수정
- 게임방 나가기 코드 수정 및 병합(웹세션으로 인해서)
> [REFACTOR] 기능 추가 및 연관된 로직 병합 (#5)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/dto/response/ImageResponseDto.java
- src/main/java/com/project/trysketch/dto/response/KeywordResponseDto.java
- src/main/java/com/project/trysketch/entity/GameFlow.java
- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/image/AmazonS3Service.java
- src/main/java/com/project/trysketch/image/ImageController.java
- src/main/java/com/project/trysketch/image/ImageService.java
- src/main/java/com/project/trysketch/image/Scheduler.java
- src/main/java/com/project/trysketch/repository/GameFlowRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/26 -> develop
- 게임 결과 이차배열로 보여주는 로직 구현
> [FEAT] 게임 결과 보여주는 로직 구현 (#26)

- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/58-> develop
- [REFACTOR] GameRoom Entity에 status -> isPlaying으로 변경
테스트 요망
> [REFACTOR] GameRoom Entity에 status -> isPlaying으로 변경

- src/main/java/com/project/trysketch/image/Scheduler.java
- src/main/java/com/project/trysketch/service/GameService.java
- 기존 각각 이미지와 키워드만 반환되는 배열에서 이미지+작성자, 키워드+작성자 로 반환되게 수정 
- 스케쥴러 04시에 작동하도록 수정
> [FEAT] 반환배열 요소 변경

- build.gradle
- src/main/java/com/project/trysketch/global/config/SwaggerConfig.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/swagger-> develop
- swagger 추가
- startGame 메소드 유저인증부 비회원 통과 가능하게 수정
> [FEAT] Swagger 추가 및 GameService-startGame 로직수정

- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/entity/ThumbImg.java
- src/main/java/com/project/trysketch/entity/User.java
- src/main/java/com/project/trysketch/redis/dto/GamerKey.java
- src/main/java/com/project/trysketch/redis/dto/GuestNickRequestDto.java
- src/main/java/com/project/trysketch/redis/entity/Guest.java
- src/main/java/com/project/trysketch/redis/service/RedisService.java
- src/main/java/com/project/trysketch/repository/ThumbImgRepository.java
- src/main/java/com/project/trysketch/service/KakaoService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/62-> develop
- 회원 정보 조회 API
- 랜덤 이미지 제공 API
> [FEAT] 회원 & 비회원 정보 조회 API 구현

- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/redis/config/RedisConfig.java
- src/main/java/com/project/trysketch/redis/dto/GamerEnum.java
- src/main/java/com/project/trysketch/redis/entity/CacheKey.java
- src/main/java/com/project/trysketch/redis/service/RedisService.java
- src/main/java/com/project/trysketch/repository/ThumbImgRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/62 -> develop
- 회원 비회원 코드 일부 추가 및 정리
- 주석 및 미사용 임포트 정리
> [REFACTOR] 를 이용한 웹소켓 채팅 구현 (#62)

- build.gradle
- src/main/java/com/project/trysketch/controller/ChatController.java
- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/dto/request/GameFlowRequestDto.java
- src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/global/config/SwaggerConfig.java
- src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/66-> develop
- 클라이언트로부터 받아올 GameFlowRequestDto 추가
- GameController의 PostMapping을 MessageMapping으로 변경
- GameService에 STOMP 메시지 추가
- 입장 관련 에러 해결
- 입장 시 방장의 readyStatus가 false로 뜨는 문제 해결
- 방장이 나간 후 다음 방장의 user id가 해당 유저의 id가 아닌 gameroom user id가 나오던 문제 해결
클라이언트와 테스트가 필요합니다.
> [FEAT] 게임 메인 로직에 WebSocket STOMP 적용

- src/main/java/com/project/trysketch/TrysKetchApplication.java
- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/redis/config/RedisConfig.java
- src/main/java/com/project/trysketch/redis/dto/TestDto.java
- src/main/java/com/project/trysketch/redis/entity/CacheKey.java
- src/main/java/com/project/trysketch/redis/entity/Guest.java
- src/main/java/com/project/trysketch/redis/repositorty/GuestRepository.java
- src/main/java/com/project/trysketch/redis/service/RedisService.java
- src/main/java/com/project/trysketch/repository/GameFlowRepository.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/62 -> develop
- Redis 캐시 적용 완료
- Redis 서버 별도로 적용
> 레디스 캐시 적용 및 코드 일부 수정

- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/repository/GameRoomRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/70 -> develop
- 초대코드 발급 위한 랜덤한 문자열 생성
- 게임방 입장시 초대코드 적용하도록 변경
> [FEAT] 초대코드 발급 기능 추가 (#70)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/service/GameService.java
> [FEAT] 게임 강제종료  api 구현

- build.gradle
- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/redis/config/RedisConfig.java
- src/main/java/com/project/trysketch/redis/entity/Guest.java
- src/main/java/com/project/trysketch/redis/repositorty/GuestRepository.java
- src/main/java/com/project/trysketch/redis/service/RedisService.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/62 -> develop
- 비회원 검증 로직 비정상 작동 해결
- 문제 해결을 위해서 spring dev tools 의존성 비활성화
> [FIX] 캐시 적용 하기 (#64)

- src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/68 -> develop
- DataMsgResponseDto의 필드명 변경했으나, 생성자에 적용하지 못해 재변경
- 게임방 목록조회 시 랜덤코드 추가
프론트와 확인했습니다
> [REFACTOR] SSE를 이용한 실시간 게임방 조회 (#68)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/dto/request/GameFlowRequestDto.java
- src/main/java/com/project/trysketch/entity/GameFlow.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
- src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/image/AmazonS3Service.java
- src/main/java/com/project/trysketch/repository/GameFlowRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/66-> develop
- WebSocketConfig SockJS 적용, Security 설정 
- Signaling Handler에 주석 추가
- 전체 방 리스트 조회 개수 10개 -> 5개로 변경
- 게임 메인 로직 WebSocket STOMP 적용
클라이언트와 테스트는 문제 없으나 추후 코드 리팩토링 필요
> [FEAT] 게임 메인 로직 WebSocket STOMP 적용

- src/main/java/com/project/trysketch/dto/request/GameRoomRequestDto.java
feature/73 -> develop
- 모든 특수문자 허용하도록 정규식 변경
> [REFACTOR] 정규식 수정 (#73)

- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/87-> develop
- 방장이 나간 후 새로운 방장의 readyStatus가 true로 바뀌도록 변경
- 방장이 나간 후 randomCode가 사라지지 않도록 Builde가 아닌 Update 용 메서드 사용
클라이언트와 테스트 후 주석 제거 하겠습니다.
> [FIX] 게임 중 예외처리 (#87)

- src/main/java/com/project/trysketch/service/KakaoService.java
feature/86 -> develop
- KakaoService 반환타입 코드 수정
> [REFACTOR] 회원, 비회원 로직 리팩토링

- src/main/java/com/project/trysketch/chatting/ChatController.java
- src/main/java/com/project/trysketch/chatting/ChatMessage.java
- src/main/java/com/project/trysketch/chatting/ChatPublisher.java
- src/main/java/com/project/trysketch/chatting/ChatSubscriber.java
- src/main/java/com/project/trysketch/redis/config/RedisConfig.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/sse/SseEmitters.java
feature/76 -> develop
- 채팅 관련 필드값 변경
- 방 나가기에 일부 코드 추가
> [REFACTOR] 웹소켓, STOMP 적용한 채팅기능 구현

- src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/rtc/Message.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/93-> develop
- 실시간으로 참여 유저의 정보가 보일 수 있도록 주고 받는 메시지 수정
- 자잘한 주석 수정
클라이언트와 테스트가 필요합니다.
> [REFACTOR] Websocket으로 게임 준비방까지 연결

- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/service/KakaoService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/96 -> develop
- 서버 배포 후 카카오톡 redirect URI 변경
- 도메인 주소로 접근 시 redirect 하기 전에 token 받아오는 부분에서 발생한 에러 처리
프론트와 확인하였습니다
> [FIX] 로그인 관련 오류 해결 (#96)

- src/main/java/com/project/trysketch/controller/UserController.java
feature/96 -> develop
- 닉네임 유효성 적용되도록 수정
포스트맨으로 확인하였습니다.
> [FIX] 닉네임 유효성 적용되도록 수정 (#96)

- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/95-> develop
- 해당 방의 title과 randomCode를 조회할 수 있는 API 추가
클라이언트와 테스트 결과 이상 없습니다.
> [REFACTOR] 방 디테일 조회 API 추가 (#95)

- src/main/java/com/project/trysketch/redis/dto/GuestNickRequestDto.java
feature/73 -> develop
- 닉네임 유효성 변경 (띄어쓰기 추가)
배포된 프론트 서버와 확인하였습니다
> [REFACTOR] 닉네임 유효성 변경 (띄어쓰기 추가) (#73)

- src/main/java/com/project/trysketch/controller/GameRoomController.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/100 -> develop
- exitGameRoom 메서드에 필요한 매개변수만 받아오는 코드로 변경
프론트 서버와 확인 결과 이상 없습니다.
> [REFACTOR] 필요한 매개변수만 받아오는 코드로 변경 (#100)

- src/main/java/com/project/trysketch/chatting/ChatController.java
- src/main/java/com/project/trysketch/chatting/ChatPublisher.java
- src/main/java/com/project/trysketch/chatting/ChatRoom.java
- src/main/java/com/project/trysketch/chatting/ChatRoomRepository.java
- src/main/java/com/project/trysketch/chatting/ChatSubscriber.java
- src/main/java/com/project/trysketch/redis/config/RedisConfig.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/76 -> develop
- 채팅 기능을 프론트에서 직접 스톰프를 사용해서 구현함으로 인해 관련 불필요 코드 주석처리
> [REFACTOR] 웹소켓, STOMP 적용한 채팅기능 구현 (#76)

- src/main/java/com/project/trysketch/dto/response/UserResponseDto.java
- src/main/java/com/project/trysketch/entity/User.java
- src/main/java/com/project/trysketch/image/ImageController.java
- src/main/java/com/project/trysketch/image/ImageService.java
회원조회, 회원 닉네임 수정 기능 구현
feature/106-> develop
- 마이페이지 회원 정보조회 기능 추가
- 마이페이지 회원 정보 중 닉네임 수정 기능 추가
Postman 테스트 완료
> [FEAT] 마이페이지 기능 구현

- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
feature/104 -> develop
- SignalingHandler 의 소켓 연결 종료 부분에 방장 정보 찾아서 메시지 발송 코드 추가
> [FIX] 재게임시 방장 여부 미전달 버그 (#104)

- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/dto/response/NaverResponseDto.java
- src/main/java/com/project/trysketch/entity/User.java
- src/main/java/com/project/trysketch/repository/UserRepository.java
- src/main/java/com/project/trysketch/service/NaverService.java
feature/112-> develop
- UserController - naverLogin 메소드 구현
- NaverService - naverLogin, getToken, getNaverUserInfo 메소드 구현
- UserRepository - findByNaverId 메소드 추가
- User 엔티티 naverId 필드 추가
- NaverResponseDto 추가
> [FEAT] 네이버 소셜로그인기능구현 (#112)

- src/main/java/com/project/trysketch/service/KakaoService.java
feature/2 -> develop
- 네이버, 구글과 코드 통일 위한 redirect URI 주소 변경
디벨로퍼 사이트의 설정도 바꿔두었습니다
> [REFACTOR] 네이버, 구글과 코드 통일 위한 redirect URI 주소 변경 (#2)

- src/main/java/com/project/trysketch/dto/request/NaverRequestDto.java
- src/main/java/com/project/trysketch/service/NaverService.java
feature/112-> develop
- 잡다한 정보가 있는 accessToken에서 필요한 정보만 추출
- Dto 위치,이름 변경
> [FIX] NaverService 버그 수정

- build.gradle
- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/dto/request/OAuthRequestDto.java
- src/main/java/com/project/trysketch/entity/User.java
- src/main/java/com/project/trysketch/repository/UserRepository.java
- src/main/java/com/project/trysketch/service/GoogleService.java
- src/main/java/com/project/trysketch/service/KakaoService.java
- src/main/java/com/project/trysketch/service/NaverService.java
feature/111 -> develop
- 구글 로그인 구현 및 프론트와 테스트 완료
- KakaoService, NaverService 랜덤 닉네임 버그 수정
> [FEAT] 구글 Oauth2 구현 및 버그 수정 (#111)

- src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/entity/UnsubmissionImg.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/repository/GameFlowRepository.java
- src/main/java/com/project/trysketch/repository/UnsubmissionImgRepository.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/122 -> develop
- 게임 중 연결 끊기더라도 정상 진행되도록 구현
- 이미지 라운드에서 제출하지 못한 경우, DB에 가지고 있는 미제출 이미지 뜨도록 함
서버 배포하여 확인했습니다
> [FIX] 게임 중 퇴장하더라도 정상 진행되도록 구현 (#122)

- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/entity/History.java
- src/main/java/com/project/trysketch/entity/User.java
- src/main/java/com/project/trysketch/service/GoogleService.java
- src/main/java/com/project/trysketch/service/HistoryService.java
feature/117-> develop
- History가 업데이트 안되던 버그 해결
서버 배포 테스트 결과 이상 없습니다.
> [FIX] History, Achievement 관련 기능 구현 (#117)

- src/main/java/com/project/trysketch/entity/History.java
- src/main/java/com/project/trysketch/service/HistoryService.java
- src/main/java/com/project/trysketch/service/KakaoService.java
- src/main/java/com/project/trysketch/service/NaverService.java
feature/117-> develop
- 기존 히스토리가 생성되고 소셜로그인시 Visit가 +1 되고 추가한 이후 getTrophyOfVisit 메소드를 통해
업적이 획득 되는것으로 변경 
서버 테스트 결과 이상 없습니다.
> 유저 활동내역 저장기능 구현, 업적 기능 구현

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/126 -> develop
- 키워드 인덱스 가져오는 코드 추가
- 키워드 인덱스 미발견 관련 코드 추가
- 키워드 인덱스 가져오기, 돌아가기 코드 추가
- GameRoom 에 키워드 인덱스 값 필드 추가
> [FEAT] 결과창 방장이 원하는 순서대로 보여주기 (#126)

- src/main/java/com/project/trysketch/dto/CacheKey.java
- src/main/java/com/project/trysketch/entity/Guest.java
- src/main/java/com/project/trysketch/repository/GuestRepository.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/5 -> develop
- 만료시에 일부 정보들이 날라가지 않는것을 발견해서 만료시간을 잠시동안 5시간으로 변경해서 확인이 필요합니다.
- 캐시 만료 시간도 이에 맞춰 2시간 정도로 변경했습니다.
> [REFACTOR] 레디스 관련 만료시간 수정 (#5)

- src/main/java/com/project/trysketch/global/rtc/Message.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
feature/131-> develop
- 불필요하게 중복되어 주고받던 타입 제거
- GameRoomService에서 관련된 method 주석처리
- Message에서 관련된 field 주석 처리
클라이언트 테스트 결과 이상 없습니다.
> [REFACTOR] SignalingHandler 리팩토링 (#131)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/133 -> develop
- GameController 및 GameService 의 getRandomKeyword 변수명 및 destination 변경
- 키워드 보내주는 로직에 플레이 인원수 및 제출 인원수도 추가
- 제출할 때 마다 현재 플레이중 인원 및 제출한 총 인원수도 반환
> [FEAT] 게임중 제출인원 표시 (#133)

- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/137 -> develop
- 게임 진행 인원 4명 미만될 시 강제종료 구현
서버 배포결과 이상 없습니다
> [FEAT] 게임 진행 인원 4명 미만될 시 강제종료 구현 (#137)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/126 -> develop
- GameController "next", "prev" 상수 추가
- GameController 키워드 번호 가져오는 메서드 명 변경
- GameService 의 다음, 이전 키워드 번호 가져오는 메서드 통합
> [REFACTOR] 게임중 제출인원 코드 리팩토링 (#126)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/120-> develop
- GameRoomService 의 exitGameRoom 에서 gameRoomUser 조회 결과 null 즉, 없을 경우 null 값을 반환
- GameService 의 submitLeftRound 에서 null 값을 받았을 경우 처리 
- SignalingHandler 강퇴시 추가 처리 및 연결 종료시에도 일부 변경
> [REFACTOR] 방장이 강퇴시 DB 에서 바로 제거 (#120)

- src/main/java/com/project/trysketch/entity/GameFlow.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/142 -> develop
- 결과 페이지의 게임결과에 유저의 프로필사진 추가
- 결과 페이지에서 게임유저 리스트 추가
배포하여 확인하였습니다
> [FEAT] 결과 페이지에 프로필사진 및 게임유저 리스트 추가 (#142)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/145-> develop
- GameController Class의 getToggleSubmit Method에 Synchronized 적용
- GameService Class에 기존 분리 되어있던 getToggleSubmit Method와 sendSubmitMessage Method 재 결합
- 초기 제시어에 띄어쓰기 추가
배포 테스트 결과 이상 없습니다.
> [FIX] 일괄 자동 제출 후 발생하던 DB 동시 접근 이슈, Synchronized 적용하여 동시성 제어 (#145)

- src/main/java/com/project/trysketch/controller/ImageController.java
- src/main/java/com/project/trysketch/dto/response/ImageLikeResponseDto.java
- src/main/java/com/project/trysketch/entity/GameFlow.java
- src/main/java/com/project/trysketch/entity/Image.java
- src/main/java/com/project/trysketch/repository/ImageLikeRepository.java
- src/main/java/com/project/trysketch/service/AmazonS3Service.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/ImageService.java
feature/153-> develop
- 무엇이든 물어보세요
서버 테스트 결과 이상 없습니다.
> [REFACTOR] 이미지 관련 파일 수정,추가 (#153)

- src/main/java/com/project/trysketch/service/GameService.java
feature/157-> develop
- 게임 진행 중도 이탈 유저의 currentKewordIndex 가 기존 +1만 되던 상황에서 최대 라운드를 넘었을 시 다시 1로 돌아오는 로직으로 변경
- 기존 제출 유저 카운트 제대로 작동하지 않던 에러 해결
클라이언트 테스트 결과 이상 없습니다.
> [FIX] 중도 이탈 유저 발생 시 에러 (#157)

- src/main/java/com/project/trysketch/controller/ImageController.java
- src/main/java/com/project/trysketch/service/ImageService.java
feature/155-> develop
- 기존 이미지 좋아요 restApi 호출시 메세지만 리턴 → 메세지 + 완료된 좋아요이미지 를 함께 리턴
- 이미지 좋아요 토글화
> [REFACTOR] 이미지 좋아요 관련 기능 수정 (#155)

- src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
- src/main/java/com/project/trysketch/global/stomp/AgentWebSocketHandlerDecoratorFactory.java
- src/main/java/com/project/trysketch/global/stomp/SubProtocolWebSocketHandlerInterceptor.java
feature/160-> develop
- 다양한 그림을 위해 버퍼 사이즈 제한 늘림
클라이언트와 테스트 필요합니다.
> [FIX] WebSocket STOMP 버퍼 사이즈 증축 (#160)

- src/main/java/com/project/trysketch/controller/ImageController.java
- src/main/java/com/project/trysketch/dto/request/UserRequestDto.java
- src/main/java/com/project/trysketch/entity/User.java
- src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/repository/ImageLikeRepository.java
- src/main/java/com/project/trysketch/repository/UnsubmissionImgRepository.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/ImageService.java
feature/159-> develop
- 기존 닉네임 수정 api → 프로필 수정( 닉네임 + 프로필 사진 ) api로 확장
- User 엔티티 nickname 필드 유니크속성 제거
- 기존 리스트를 반환하던 gameService의 게임 결과에서 map형태의 key-value 형태로 반환하도록 변경
서버 테스트 결과 이상 없습니다.
> 유저 프로필변경 기능 수정, 이미지 좋아요기능 보완

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/163-> develop
- GameService 클래스의 getToggleSubmit 메소드에서 식별자 값인 id를 엔티티에 직접 지정한 후 save 하여 update 쿼리 호출
다수의 인원과 여러번 테스트가 필요합니다.
> [FIX] 자동 제출 시 게임이 진행되지 않는 에러 (#163)

- src/main/java/com/project/trysketch/controller/MypageController.java
- src/main/java/com/project/trysketch/entity/GameFlow.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/HistoryService.java
- src/main/java/com/project/trysketch/service/MypageService.java
feature/170-> develop
- gameflow update 메소드 리턴값 변경
- gameroomuser 엔티티 userPlayTime 필드 casecade 옵션 추가
- 업적이 달성되면 프론트에게 알려줄 메세지 추가
> [FEAT] 3종 업적 관련기능 추가 (#170)

- src/main/java/com/project/trysketch/controller/MypageController.java
- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/dto/response/AchievementResponseDto.java
- src/main/java/com/project/trysketch/entity/Achievement.java
- src/main/java/com/project/trysketch/entity/GameRoomUser.java
- src/main/java/com/project/trysketch/global/utill/AchievementCode.java
- src/main/java/com/project/trysketch/service/HistoryService.java
- src/main/java/com/project/trysketch/service/MypageService.java
feature/170-> develop
- 마이페이지 관련 뱃지조회 api 구현
> [FEAT] 마이페이지에서 달성된 업적 조회기능 추가 (#170)

- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/service/GoogleService.java
- src/main/java/com/project/trysketch/service/HistoryService.java
- src/main/java/com/project/trysketch/service/KakaoService.java
- src/main/java/com/project/trysketch/service/NaverService.java
feature/170-> develop
- 3종 소셜로그인 반환값 변경
- StatusMsgCode 추가
> [FEAT]  로그인 업적 달성시 메세지와 함께 달성한 업적이름 반환 (#170)

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/177-> develop
- GameController에 synchronized  적용
- StatusMsgCode 코드 추가
- GameService - saveImage 코드 경량화
서버 테스트 결과 이상 없습니다.
> [REFECTOR] GameService 코드 리팩토링, 자동제출 기능추가

- src/main/java/com/project/trysketch/service/GameService.java
- src/main/java/com/project/trysketch/service/GoogleService.java
- src/main/java/com/project/trysketch/service/HistoryService.java
- src/main/java/com/project/trysketch/service/KakaoService.java
- src/main/java/com/project/trysketch/service/NaverService.java
feature/179-> develop
- getTrophyOfTime 와 getTrophyOfTrial 가 각각의 achievement의 list를 반환하도록 변경
- 업적에 대한 응답이 달성한 업적이 있을 경우에만 하도록 변경
> 업적관련 기능 추가 및 변경

- src/main/java/com/project/trysketch/controller/GameController.java
- src/main/java/com/project/trysketch/entity/GameRoom.java
- src/main/java/com/project/trysketch/entity/Image.java
- src/main/java/com/project/trysketch/global/utill/sse/SseController.java
- src/main/java/com/project/trysketch/global/utill/sse/SseEmitters.java
- src/main/java/com/project/trysketch/service/GameRoomService.java
- src/main/java/com/project/trysketch/service/GameService.java
feature/68 -> develop
- 방에서 나오더라도 끊김없이 데이터 잘 받아오도록 버그 수정
- 방 인원, 게임진행 상태도 받도록 수정
서버 배포 후 확인결과 이상 없습니다.
> [FEAT] SSE 적용시 발생하던 오류 해결 및 인원수까지 반영되도록 수정(#68)

- src/main/java/com/project/trysketch/service/KakaoService.java
feature/182 -> develop
- OAuth2.0 카카오 로그인관련 - REST API키 숨김처리
서버 배포결과 이상 없습니다
> [REFACTOR] OAuth2.0 카카오 로그인관련 - REST API키 숨김처리 (#182)

- src/main/java/com/project/trysketch/controller/UserController.java
- src/main/java/com/project/trysketch/entity/RefreshToken.java
- src/main/java/com/project/trysketch/global/config/RedisConfig.java
- src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
- src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
- src/main/java/com/project/trysketch/global/jwt/RefreshToken.java
- src/main/java/com/project/trysketch/repository/RefreshTokenRepository.java
- src/main/java/com/project/trysketch/service/GuestService.java
- src/main/java/com/project/trysketch/service/SocialLoginService.java
- src/main/java/com/project/trysketch/service/UserService.java
feature/190 -> develop
- RefreshToken 적용 완료했습니다.
- AccessToken 30분 / RefreshToken 7일 으로 만료시간 변경
> [FEAT] 로그인 시 RefreshToken 적용 (#190)
